services:
  # Sonarr Instances - Multiple for quality/language combinations
  sonarr-1080p-en:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr-1080p-en
    depends_on:
      - jellyfin
    restart: unless-stopped
    ports:
      - "8989:8989"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ./sonarr/1080p-en:/config
      - ./jellyfin/media:/media
      - ./downloads:/downloads
      - ./scripts:/scripts:ro  # Custom scripts directory
    networks:
      - traefik

  sonarr-1080p-de:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr-1080p-de
    depends_on:
      - jellyfin
    restart: unless-stopped
    ports:
      - "8990:8989"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ./sonarr/1080p-de:/config
      - ./jellyfin/media:/media
      - ./downloads:/downloads
      - ./scripts:/scripts:ro
    networks:
      - traefik

  sonarr-2160p-en:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr-2160p-en
    depends_on:
      - jellyfin
    restart: unless-stopped
    ports:
      - "8991:8989"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ./sonarr/2160p-en:/config
      - ./jellyfin/media:/media
      - ./downloads:/downloads
      - ./scripts:/scripts:ro
    networks:
      - traefik

  sonarr-2160p-de:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr-2160p-de
    depends_on:
      - jellyfin
    restart: unless-stopped
    ports:
      - "8992:8989"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ./sonarr/2160p-de:/config
      - ./jellyfin/media:/media
      - ./downloads:/downloads
      - ./scripts:/scripts:ro
    networks:
      - traefik

  # Radarr Instances - Multiple for quality/language combinations
  radarr-1080p-en:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr-1080p-en
    depends_on:
      - jellyfin
    restart: unless-stopped
    ports:
      - "7878:7878"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ./radarr/1080p-en:/config
      - ./jellyfin/media:/media
      - ./downloads:/downloads
      - ./scripts:/scripts:ro
    networks:
      - traefik

  radarr-1080p-de:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr-1080p-de
    depends_on:
      - jellyfin
    restart: unless-stopped
    ports:
      - "7879:7878"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ./radarr/1080p-de:/config
      - ./jellyfin/media:/media
      - ./downloads:/downloads
      - ./scripts:/scripts:ro
    networks:
      - traefik

  radarr-2160p-en:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr-2160p-en
    depends_on:
      - jellyfin
    restart: unless-stopped
    ports:
      - "7880:7878"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ./radarr/2160p-en:/config
      - ./jellyfin/media:/media
      - ./downloads:/downloads
      - ./scripts:/scripts:ro
    networks:
      - traefik

  radarr-2160p-de:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr-2160p-de
    depends_on:
      - jellyfin
    restart: unless-stopped
    ports:
      - "7881:7878"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ./radarr/2160p-de:/config
      - ./jellyfin/media:/media
      - ./downloads:/downloads
      - ./scripts:/scripts:ro
    networks:
      - traefik

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    depends_on:
      - sonarr-1080p-en
      - sonarr-1080p-de
      - sonarr-2160p-en
      - sonarr-2160p-de
      - radarr-1080p-en
      - radarr-1080p-de
      - radarr-2160p-en
      - radarr-2160p-de
    restart: unless-stopped
    ports:
      - "9696:9696"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ./prowlarr/config:/config
    networks:
      - traefik

  bazarr-1080p-en:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr-1080p-en
    depends_on:
      - sonarr-1080p-en
      - radarr-1080p-en
    restart: unless-stopped
    ports:
      - "6767:6767"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ./bazarr/1080p-en/config:/config
      - ./jellyfin/media:/media
      - ./downloads:/downloads
    networks:
      - traefik

  bazarr-1080p-de:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr-1080p-de
    depends_on:
      - sonarr-1080p-de
      - radarr-1080p-de
    restart: unless-stopped
    ports:
      - "6768:6767"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ./bazarr/1080p-de/config:/config
      - ./jellyfin/media:/media
      - ./downloads:/downloads
    networks:
      - traefik

  bazarr-2160p-en:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr-2160p-en
    depends_on:
      - sonarr-2160p-en
      - radarr-2160p-en
    restart: unless-stopped
    ports:
      - "6769:6767"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ./bazarr/2160p-en/config:/config
      - ./jellyfin/media:/media
      - ./downloads:/downloads
    networks:
      - traefik

  bazarr-2160p-de:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr-2160p-de
    depends_on:
      - sonarr-2160p-de
      - radarr-2160p-de
    restart: unless-stopped
    ports:
      - "6770:6767"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ./bazarr/2160p-de/config:/config
      - ./jellyfin/media:/media
      - ./downloads:/downloads
    networks:
      - traefik

  # Configarr - Multi-instance custom format and quality profile management
  configarr:
    image: ghcr.io/raydak-labs/configarr:latest
    container_name: configarr
    depends_on:
      - radarr-1080p-en
      - radarr-1080p-de
      - radarr-2160p-en
      - radarr-2160p-de
    restart: unless-stopped
    environment:
      - TZ=${TZ}
      - RADARR_EN_1080P_API_KEY=${RADARR_EN_1080P_API_KEY}
      - RADARR_DE_1080P_API_KEY=${RADARR_DE_1080P_API_KEY}
      - RADARR_EN_2160P_API_KEY=${RADARR_EN_2160P_API_KEY}
      - RADARR_DE_2160P_API_KEY=${RADARR_DE_2160P_API_KEY}
      - SONARR_EN_1080P_API_KEY=${SONARR_EN_1080P_API_KEY}
      - SONARR_DE_1080P_API_KEY=${SONARR_DE_1080P_API_KEY}
      - SONARR_EN_2160P_API_KEY=${SONARR_EN_2160P_API_KEY}
      - SONARR_DE_2160P_API_KEY=${SONARR_DE_2160P_API_KEY}
    volumes:
      - ./configarr:/app/config
    networks:
      - traefik
