###################################################################################################
# RADARR Configuration Templates
# Recyclarr Configuration Templates modifed to fit multi-instance setups
###################################################################################################
# Instance Definition: https://recyclarr.dev/wiki/yaml/config-reference/basic/

sonarrEnabled: true
radarrEnabled: true
whisparrEnabled: false
readarrEnabled: false
lidarrEnabled: false

radarr:
  hd-bluray-web-ger:
    base_url: http://radarr-1080p-de:7878
    api_key: !env RADARR_DE_1080P_API_KEY

    include:
      - template: radarr-quality-definition-movie
      - template: radarr-custom-formats-hd-bluray-web-german
      - template: radarr-quality-profile-hd-bluray-web-german

    media_naming:
      folder: jellyfin
      movie:
        rename: true
        standard: jellyfin

    quality_profiles:
      - name: HD Bluray + WEB (GER)
        min_format_score: 10000 # Uncomment this line to skip English Releases

    custom_formats:
      - trash_ids:
          - b6832f586342ef70d9c128d40c07b872 # Bad Dual Groups
          # - ae9b7c9ebde1f3bd336a8cbd1ec4c5e5 # No-RlsGroup
          - 7357cf5161efbf8c4d5d0c30b4815ee2 # Obfuscated
          - 5c44f52a8714fdd79bb4d98e2673be1f # Retags
          - f537cf427b64c38c8e36298f657e4828 # Scene
        assign_scores_to:
          - name: HD Bluray + WEB (GER)

### x265 - IMPORTANT: Only use on of the options below.
      - trash_ids:
          - 839bea857ed2c0a8e084f3cbdbd65ecb
        assign_scores_to:
          - name: HD Bluray + WEB (GER)

### Generated Dynamic HDR
      - trash_ids:
          - e6886871085226c3da1830830146846c
        assign_scores_to:
          - name: HD Bluray + WEB (GER)
            score: -35000

  hd-bluray-web:
    base_url: http://radarr-1080p-en:7878
    api_key: !env RADARR_EN_1080P_API_KEY

    include:
      - template: radarr-quality-definition-movie
      - template: radarr-quality-profile-hd-bluray-web
      - template: radarr-custom-formats-hd-bluray-web

    media_naming:
      folder: jellyfin
      movie:
        rename: true
        standard: jellyfin

    custom_formats:
      # Not English
      # - trash_ids: ["0dc8aec3bd1c47cd6c40c46ecd27e846"]   # Language: Not English
        # assign_scores_to:
          # - name: HD Bluray + WEB
      - trash_ids:
          - b6832f586342ef70d9c128d40c07b872 # Bad Dual Groups
          - cc444569854e9de0b084ab2b8b1532b2 # Black and White Editions
          # - ae9b7c9ebde1f3bd336a8cbd1ec4c5e5 # No-RlsGroup
          - 7357cf5161efbf8c4d5d0c30b4815ee2 # Obfuscated
          - 5c44f52a8714fdd79bb4d98e2673be1f # Retags
          - f537cf427b64c38c8e36298f657e4828 # Scene
        assign_scores_to:
          - name: HD Bluray + WEB

      - trash_ids:
          # Uncomment the next six lines to allow x265 HD releases with HDR/DV
          # - dc98083864ea246d05a42df0d05f81cc # x265 (HD)
        # assign_scores_to:
          # - name: HD Bluray + WEB
            # score: 0
      # - trash_ids:
          # - 839bea857ed2c0a8e084f3cbdbd65ecb # x265 (no HDR/DV)
        assign_scores_to:
          - name: HD Bluray + WEB
  
  uhd-bluray-web-ger:
    base_url: http://radarr-2160p-de:7878
    api_key: !env RADARR_DE_2160P_API_KEY

    include:
      - template: radarr-quality-definition-movie
      - template: radarr-custom-formats-uhd-bluray-web-german
      - template: radarr-quality-profile-uhd-bluray-web-german

    media_naming:
      folder: jellyfin
      movie:
        rename: true
        standard: jellyfin

    quality_profiles:
      - name: UHD Bluray + WEB (GER)
        min_format_score: 10000
    custom_formats:
### Audio
      - trash_ids:
# Uncomment the next section to enable Advanced Audio Formats
#          - 496f355514737f7d83bf7aa4d24f8169 # TrueHD Atmos
#          - 2f22d89048b01681dde8afe203bf2e95 # DTS X
#          - 417804f7f2c4308c1f4c5d380d4c4475 # ATMOS (undefined)
#          - 1af239278386be2919e1bcee0bde047e # DD+ ATMOS
#          - 3cafb66171b47f226146a0770576870f # TrueHD
#          - dcf3ec6938fa32445f590a4da84256cd # DTS-HD MA
#          - a570d4a0e56a2874b64e5bfa55202a1b # FLAC
#          - e7c2fcae07cbada050a0af3357491d7b # PCM
#          - 8e109e50e0a0b83a5098b056e13bf6db # DTS-HD HRA
#          - 185f1dd7264c4562b9022d963ac37424 # DD+
#          - f9f847ac70a0af62ea4a08280b859636 # DTS-ES
#          - 1c1a4c5e823891c75bc50380a6866f73 # DTS
#          - 240770601cc226190c367ef59aba7463 # AAC
#          - c2998bd0d90ed5621d8df281e839436e # DD
        assign_scores_to:
          - name: UHD Bluray + WEB (GER)
### Optional
      - trash_ids:
          - b6832f586342ef70d9c128d40c07b872 # Bad Dual Groups
          # - ae9b7c9ebde1f3bd336a8cbd1ec4c5e5 # No-RlsGroup
          - 7357cf5161efbf8c4d5d0c30b4815ee2 # Obfuscated
          - 5c44f52a8714fdd79bb4d98e2673be1f # Retags
          - f537cf427b64c38c8e36298f657e4828 # Scene
        assign_scores_to:
          - name: UHD Bluray + WEB (GER)

### HDR / DV
      - trash_ids:
# Comment out the next line if you and all of your users' setups are fully DV compatible
          - 923b6abef9b17f937fab56cfcf89e1f1 # DV (WEBDL)

# HDR10+ Boost - Uncomment the next two lines if any of your devices DO support HDR10+
#          - b17886cb4158d9fea189859409975758 # HDR10Plus Boost
#          - 55a5b50cb416dea5a50c4955896217ab # DV HDR10+ Boost
        assign_scores_to:
          - name: UHD Bluray + WEB (GER)

### Optional SDR
# Only ever use ONE of the following custom formats:
# SDR - block ALL SDR releases
# SDR (no WEBDL) - block UHD/4k Remux and Bluray encode SDR releases, but allow SDR WEB
      - trash_ids:
#          - 9c38ebb7384dada637be8899efa68e6f # SDR
          - 25c12f78430a3a23413652cbd1d48d77 # SDR (no WEBDL)
        assign_scores_to:
          - name: UHD Bluray + WEB (GER)

### x265 - IMPORTANT: Only use on of the options below.
      - trash_ids:
#          - 839bea857ed2c0a8e084f3cbdbd65ecb # Uncomment this line to allow HDR/DV x265 HD releases
        assign_scores_to:
          - name: UHD Bluray + WEB (GER)

      - trash_ids:
          - dc98083864ea246d05a42df0d05f81cc # Uncomment this line to block all x265 HD releases
        assign_scores_to:
          - name: UHD Bluray + WEB (GER)
            score: -35000

### Generated Dynamic HDR
      - trash_ids:
          - e6886871085226c3da1830830146846c # Uncomment this line to block Generated Dynamic HDR
        assign_scores_to:
          - name: UHD Bluray + WEB (GER)
            score: -35000
  
  uhd-bluray-web:
    base_url: http://radarr-2160p-en:7878
    api_key: !env RADARR_EN_2160P_API_KEY

    include:
      # Comment out any of the following includes to disable them
      - template: radarr-quality-definition-movie
      - template: radarr-quality-profile-uhd-bluray-web
      - template: radarr-custom-formats-uhd-bluray-web

    media_naming:
      folder: jellyfin
      movie:
        rename: true
        standard: jellyfin

# Custom Formats: https://recyclarr.dev/wiki/yaml/config-reference/custom-formats/
    custom_formats:
      # Not English
      # - trash_ids: ["0dc8aec3bd1c47cd6c40c46ecd27e846"]   # Language: Not English
        # assign_scores_to:
          # - name: UHD Bluray + WEB
      # Audio
      - trash_ids:
          # Uncomment the next section to enable Advanced Audio Formats
          # - 496f355514737f7d83bf7aa4d24f8169 # TrueHD Atmos
          # - 2f22d89048b01681dde8afe203bf2e95 # DTS X
          # - 417804f7f2c4308c1f4c5d380d4c4475 # ATMOS (undefined)
          # - 1af239278386be2919e1bcee0bde047e # DD+ ATMOS
          # - 3cafb66171b47f226146a0770576870f # TrueHD
          # - dcf3ec6938fa32445f590a4da84256cd # DTS-HD MA
          # - a570d4a0e56a2874b64e5bfa55202a1b # FLAC
          # - e7c2fcae07cbada050a0af3357491d7b # PCM
          # - 8e109e50e0a0b83a5098b056e13bf6db # DTS-HD HRA
          # - 185f1dd7264c4562b9022d963ac37424 # DD+
          # - f9f847ac70a0af62ea4a08280b859636 # DTS-ES
          # - 1c1a4c5e823891c75bc50380a6866f73 # DTS
          # - 240770601cc226190c367ef59aba7463 # AAC
          # - c2998bd0d90ed5621d8df281e839436e # DD
        assign_scores_to:
          - name: UHD Bluray + WEB
      # Optional
      - trash_ids:
          - b6832f586342ef70d9c128d40c07b872 # Bad Dual Groups
          - cc444569854e9de0b084ab2b8b1532b2 # Black and White Editions
          # - ae9b7c9ebde1f3bd336a8cbd1ec4c5e5 # No-RlsGroup
          - 7357cf5161efbf8c4d5d0c30b4815ee2 # Obfuscated
          - 5c44f52a8714fdd79bb4d98e2673be1f # Retags
          - f537cf427b64c38c8e36298f657e4828 # Scene
        assign_scores_to:
          - name: UHD Bluray + WEB
      - trash_ids:
          # Comment out the next line if you and all of your users' setups are fully DV compatible
          - 923b6abef9b17f937fab56cfcf89e1f1 # DV (WEBDL)

          # HDR10+ Boost - Uncomment the next two lines if any of your devices DO support HDR10+
          # - b17886cb4158d9fea189859409975758 # HDR10Plus Boost
          # - 55a5b50cb416dea5a50c4955896217ab # DV HDR10+ Boost
        assign_scores_to:
          - name: UHD Bluray + WEB

      # Optional SDR
      # Only ever use ONE of the following custom formats:
      # SDR - block ALL SDR releases
      # SDR (no WEBDL) - block UHD/4k Remux and Bluray encode SDR releases, but allow SDR WEB
      - trash_ids:
          # - 9c38ebb7384dada637be8899efa68e6f # SDR
          - 25c12f78430a3a23413652cbd1d48d77 # SDR (no WEBDL)
        assign_scores_to:
          - name: UHD Bluray + WEB

# ------------------------------------------------------------------

###################################################################################################
# RADARR Configuration Templates
# Recyclarr Configuration Templates modifed to fit multi-instance setups
###################################################################################################
# Instance Definition: https://recyclarr.dev/wiki/yaml/config-reference/basic/

sonarr:
  hd-bluray-web-ger:
    base_url: http://sonarr-1080p-de:8989
    api_key: !env SONARR_DE_1080P_API_KEY

    include:
      - template: sonarr-quality-definition-series
      - template: sonarr-v4-custom-formats-hd-bluray-web-german
      - template: sonarr-v4-quality-profile-hd-bluray-web-german

    media_naming:
      series: jellyfin
      season: default
      episodes:
        rename: true
        standard: default
        daily: default
        anime: default

    quality_profiles:
      - name: HD Bluray + WEB (GER)
        min_format_score: 10000

    custom_formats:
### Optional
      - trash_ids:
          - 32b367365729d530ca1c124a0b180c64 # Bad Dual Groups
          # - 82d40da2bc6923f41e14394075dd4b03 # No-RlsGroup
          - e1a997ddb54e3ecbfe06341ad323c458 # Obfuscated
          - 06d66ab109d4d2eddb2794d21526d140 # Retags
          - 1b3994c551cbb92a2c781af061f4ab44 # Scene
        assign_scores_to:
          - name: HD Bluray + WEB (GER)

### x265 - IMPORTANT: Only use on of the options below.
      - trash_ids:
          - 47435ece6b99a0b477caf360e79ba0bb # Uncomment this to block all x265 HD releases
        assign_scores_to:
          - name: HD Bluray + WEB (GER)
            score: -35000
  
  web-1080p-v4:
    base_url: http://sonarr-1080p-en:8989
    api_key: !env SONARR_EN_1080P_API_KEY

    include:
      # Comment out any of the following includes to disable them
      - template: sonarr-quality-definition-series
      # Choose between the standard or alternative quality profile setup (choose one only)
      - template: sonarr-v4-quality-profile-web-1080p
      # - template: sonarr-v4-quality-profile-web-1080p-alternative
      - template: sonarr-v4-custom-formats-web-1080p

    media_naming:
      series: jellyfin
      season: default
      episodes:
        rename: true
        standard: default
        daily: default
        anime: default

# Custom Formats: https://recyclarr.dev/wiki/yaml/config-reference/custom-formats/
    custom_formats:
      # Not English
      # - trash_ids: ["69aa1e159f97d860440b04cd6d590c4f"]   # Language: Not English
        # assign_scores_to:
          # - name: WEB-1080p
      # Optional
      - trash_ids:
          - 32b367365729d530ca1c124a0b180c64 # Bad Dual Groups
          # - 82d40da2bc6923f41e14394075dd4b03 # No-RlsGroup
          - e1a997ddb54e3ecbfe06341ad323c458 # Obfuscated
          - 06d66ab109d4d2eddb2794d21526d140 # Retags
          - 1b3994c551cbb92a2c781af061f4ab44 # Scene
        assign_scores_to:
          - name: WEB-1080p

      - trash_ids:
          - 9b64dff695c2115facf1b6ea59c9bd07 # x265 (no HDR/DV)
        assign_scores_to:
          - name: WEB-1080p
  
  uhd-bluray-web-ger:
    base_url: http://sonarr-2160p-de:8989
    api_key: !env SONARR_DE_2160P_API_KEY

    include:
      - template: sonarr-quality-definition-series
      - template: sonarr-v4-custom-formats-uhd-bluray-web-german
      - template: sonarr-v4-quality-profile-uhd-bluray-web-german

    media_naming:
      series: jellyfin
      season: default
      episodes:
        rename: true
        standard: default
        daily: default
        anime: default

    quality_profiles:
      - name: UHD Bluray + WEB (GER)
        min_format_score: 10000
    custom_formats:
### Optional
      - trash_ids:
          - 32b367365729d530ca1c124a0b180c64 # Bad Dual Groups
          # - 82d40da2bc6923f41e14394075dd4b03 # No-RlsGroup
          - e1a997ddb54e3ecbfe06341ad323c458 # Obfuscated
          - 06d66ab109d4d2eddb2794d21526d140 # Retags
          - 1b3994c551cbb92a2c781af061f4ab44 # Scene
        assign_scores_to:
          - name: UHD Bluray + WEB (GER)

### HDR / DV
      - trash_ids:
# Comment out the next line if you and all of your users' setups are fully DV compatible
          - 9b27ab6498ec0f31a3353992e19434ca # DV (WEBDL)

# HDR10+ Boost - Uncomment the next two lines if any of your devices DO support HDR10+
#          - 0dad0a507451acddd754fe6dc3a7f5e7 # HDR10Plus Boost
#          - 385e9e8581d33133c3961bdcdeffb7b4 # DV HDR10+ Boost
        assign_scores_to:
          - name: UHD Bluray + WEB (GER)

### Optional SDR
# Only ever use ONE of the following custom formats:
# SDR - block ALL SDR releases
# SDR (no WEBDL) - block UHD/4k Remux and Bluray encode SDR releases, but allow SDR WEB
      - trash_ids:
#          - 2016d1676f5ee13a5b7257ff86ac9a93 # SDR
          - 83304f261cf516bb208c18c54c0adf97 # SDR (no WEBDL)
        assign_scores_to:
          - name: UHD Bluray + WEB (GER)

### x265 - IMPORTANT: Only use on of below options.
      - trash_ids:
          - 47435ece6b99a0b477caf360e79ba0bb # Uncomment this to block all x265 HD releases
        assign_scores_to:
          - name: UHD Bluray + WEB (GER)
            score: -35000

  web-2160p-v4:
    base_url: http://sonarr-2160p-en:8989
    api_key: !env SONARR_EN_2160P_API_KEY

    include:
      # Comment out any of the following includes to disable them
      - template: sonarr-quality-definition-series
      # Choose between the standard or alternative quality profile setup (choose one only)
      - template: sonarr-v4-quality-profile-web-2160p
      # - template: sonarr-v4-quality-profile-web-2160p-alternative
      - template: sonarr-v4-custom-formats-web-2160p

    media_naming:
      series: jellyfin
      season: default
      episodes:
        rename: true
        standard: default
        daily: default
        anime: default

# Custom Formats: https://recyclarr.dev/wiki/yaml/config-reference/custom-formats/
    custom_formats:
      # Not English
      # - trash_ids: ["69aa1e159f97d860440b04cd6d590c4f"]   # Language: Not English
        # assign_scores_to:
          # - name: WEB-2160p
      # HDR Formats
      - trash_ids:
          # Comment out the next line if you and all of your users' setups are fully DV compatible
          - 9b27ab6498ec0f31a3353992e19434ca # DV (WEBDL)

          # HDR10+ Boost - Uncomment the next two lines if any of your devices DO support HDR10+
          # - 0dad0a507451acddd754fe6dc3a7f5e7 # HDR10+ Boost
          # - 385e9e8581d33133c3961bdcdeffb7b4 # DV HDR10+ Boost
        assign_scores_to:
          - name: WEB-2160p

      # Optional
      - trash_ids:
          - 32b367365729d530ca1c124a0b180c64 # Bad Dual Groups
          # - 82d40da2bc6923f41e14394075dd4b03 # No-RlsGroup
          - e1a997ddb54e3ecbfe06341ad323c458 # Obfuscated
          - 06d66ab109d4d2eddb2794d21526d140 # Retags
          - 1b3994c551cbb92a2c781af061f4ab44 # Scene
        assign_scores_to:
          - name: WEB-2160p
      # Optional SDR
      # Only ever use ONE of the following custom formats:
      # SDR - block ALL SDR releases
      # SDR (no WEBDL) - block UHD/4k Remux and Bluray encode SDR releases, but allow SDR WEB
      - trash_ids:
          # - 2016d1676f5ee13a5b7257ff86ac9a93 # SDR
          - 83304f261cf516bb208c18c54c0adf97 # SDR (no WEBDL)
        assign_scores_to:
          - name: WEB-2160p